import { gameCommonManifest, stgCommonManifest } from "@/assets/manifest";

/** @description 主资源 */
const gameManifest: Record<string, string> = {
  number_one: "moneyComing/assets/font/nums_one/number.fnt",
  number_two: "moneyComing/assets/font/nums_two/number.fnt",
  number_three: "moneyComing/assets/font/nums_three/number.fnt",
  number_wheel_nums_green: "moneyComing/assets/font/wheel_nums_green/number.fnt",
  number_wheel_nums_white: "moneyComing/assets/font/wheel_nums_white/number.fnt",
  number_wheel_nums_yellow: "moneyComing/assets/font/wheel_nums_yellow/number.fnt",

  game_bg: "moneyComing/assets/img/game/bg.png",

  into_play_btn: "moneyComing/assets/img/game/into/btn.png",

  winMore_close: "moneyComing/assets/img/game/winMore/close.png",
  winMore_dialog_bg: "moneyComing/assets/img/game/winMore/dialog_bg.png",
  winMore_img_1: "moneyComing/assets/img/game/winMore/img_1.png",
  winMore_img_2: "moneyComing/assets/img/game/winMore/img_2.png",
  winMore_logo: "moneyComing/assets/img/game/winMore/logo.png",
  winMore_selected: "moneyComing/assets/img/game/winMore/selected.png",
  winMore_title_zh: "moneyComing/assets/img/game/winMore/title_zh.png",
  winMore_title_tc: "moneyComing/assets/img/game/winMore/title_tc.png",
  winMore_title_en: "moneyComing/assets/img/game/winMore/title_en.png",

  autoSetting_bottom_bg: "moneyComing/assets/img/game/autoSetting/bottom_bg.png",
  autoSetting_btn: "moneyComing/assets/img/game/autoSetting/btn.png",
  autoSetting_close: "moneyComing/assets/img/game/autoSetting/close.png",
  autoSetting_count_bg: "moneyComing/assets/img/game/autoSetting/count_bg.png",
  autoSetting_logo: "moneyComing/assets/img/game/autoSetting/logo.png",
  autoSetting_top_bg: "moneyComing/assets/img/game/autoSetting/top_bg.png",

  winDialog_amount_bg: "moneyComing/assets/img/game/winDialog/amount_bg.png",
  winDialog_big_win: "moneyComing/assets/img/game/winDialog/big_win.png",
  winDialog_mege_win: "moneyComing/assets/img/game/winDialog/mege_win.png",
  winDialog_super_win: "moneyComing/assets/img/game/winDialog/super_win.png",

  frame_top: "moneyComing/assets/img/game/frame/top.png",
  frame_bottom: "moneyComing/assets/img/game/frame/bottom.png",
  frame_axis_bg: "moneyComing/assets/img/game/frame/axis_bg.png",
  frame_axis_mask: "moneyComing/assets/img/game/frame/axis_mask.png",
  frame_axis_base: "moneyComing/assets/img/game/frame/axis_base.png",
  frame_lock: "moneyComing/assets/img/game/frame/lock.png",
  frame_lock_mask: "moneyComing/assets/img/game/frame/lock_mask.png",

  wheel_lock: "moneyComing/assets/img/game/frame/wheel/lock.png",
  wheel_tip_bg: "moneyComing/assets/img/game/frame/wheel/tip_bg.png",
  wheel_base_green: "moneyComing/assets/img/game/frame/wheel/base_green.png",
  wheel_base_red: "moneyComing/assets/img/game/frame/wheel/base_red.png",
  wheel_plate_base: "moneyComing/assets/img/game/frame/wheel/plate_base.png",
  wheel_red_light_dot: "moneyComing/assets/img/game/frame/wheel/red_light_dot.png",
  wheel_green_light_dot: "moneyComing/assets/img/game/frame/wheel/green_light_dot.png",
  wheel_heartbroken: "moneyComing/assets/img/game/frame/wheel/heartbroken.png",
  wheel_wheel_nums_one: "moneyComing/assets/img/game/frame/wheel/wheel_nums_0.png",
  wheel_wheel_nums_two: "moneyComing/assets/img/game/frame/wheel/wheel_nums_1.png",
  wheel_wheel_nums_three: "moneyComing/assets/img/game/frame/wheel/wheel_nums_2.png",
  wheel_wheel_nums_four: "moneyComing/assets/img/game/frame/wheel/wheel_nums_3.png",

  status_big_blue: "moneyComing/assets/img/game/frame/status/big_blue.png",
  status_big_green: "moneyComing/assets/img/game/frame/status/big_green.png",
  status_big_red: "moneyComing/assets/img/game/frame/status/big_red.png",
  status_small_one: "moneyComing/assets/img/game/frame/status/small_one.png",
  status_small_two: "moneyComing/assets/img/game/frame/status/small_two.png",
  status_respin: "moneyComing/assets/img/game/frame/status/respin.png",
  status_scatter: "moneyComing/assets/img/game/frame/status/scatter.png",
  status_super_scatter: "moneyComing/assets/img/game/frame/status/super_scatter.png",
  status_arrow: "moneyComing/assets/img/game/frame/status/arrow.png",
  status_special_respin: "moneyComing/assets/img/game/frame/status/special_respin.png",
  status_special_x2: "moneyComing/assets/img/game/frame/status/special_x2.png",
  status_special_x5: "moneyComing/assets/img/game/frame/status/special_x5.png",

  axisIcon_0: "moneyComing/assets/img/game/axisIcon/0.png",
  axisIcon_00: "moneyComing/assets/img/game/axisIcon/00.png",
  axisIcon_1: "moneyComing/assets/img/game/axisIcon/1.png",
  axisIcon_5: "moneyComing/assets/img/game/axisIcon/5.png",
  axisIcon_10: "moneyComing/assets/img/game/axisIcon/10.png",
  axisIcon_all: "moneyComing/assets/img/game/axisIcon/all.png",
  axisIcon_scatter_green: "moneyComing/assets/img/game/axisIcon/scatter_green.png",
  axisIcon_scatter_red: "moneyComing/assets/img/game/axisIcon/scatter_red.png",
  axisIcon_x2: "moneyComing/assets/img/game/axisIcon/x2.png",
  axisIcon_x5: "moneyComing/assets/img/game/axisIcon/x5.png",
  axisIcon_x10: "moneyComing/assets/img/game/axisIcon/x10.png",

  toolbar_amount_list_bg: "moneyComing/assets/img/game/toolbar/amount_list_bg.png",
  toolbar_amount_selected: "moneyComing/assets/img/game/toolbar/amount_selected.png",
  toolbar_bet_amount_bg: "moneyComing/assets/img/game/toolbar/bet_amount_bg.png",

  toolbar_bet_level_bg: "moneyComing/assets/img/game/toolbar/bet_level_bg.png",
  toolbar_arrow: "moneyComing/assets/img/game/toolbar/arrow.png",
  toolbar_btn_bg: "moneyComing/assets/img/game/toolbar/btn_bg.png",
  toolbar_option_bg: "moneyComing/assets/img/game/toolbar/option_bg.png",
  toolbar_start: "moneyComing/assets/img/game/toolbar/start.png",
  toolbar_stop: "moneyComing/assets/img/game/toolbar/stop.png",
  toolbar_bg: "moneyComing/assets/img/game/toolbar/bg.png",
  toolbar_more: "moneyComing/assets/img/game/toolbar/more.png",
  toolbar_more_hover: "moneyComing/assets/img/game/toolbar/more_hover.png",
  toolbar_win_label: "moneyComing/assets/img/game/toolbar/win_label.png",
  toolbar_max_en: "moneyComing/assets/img/game/toolbar/max_en.png",
  toolbar_max_zh: "moneyComing/assets/img/game/toolbar/max_zh.png",
  toolbar_min_en: "moneyComing/assets/img/game/toolbar/min_en.png",
  toolbar_min_max_bg: "moneyComing/assets/img/game/toolbar/min_max_bg.png",
  toolbar_min_zh: "moneyComing/assets/img/game/toolbar/min_zh.png",
  toolbar_max_hover_en: "moneyComing/assets/img/game/toolbar/max_hover_en.png",
  toolbar_max_hover_zh: "moneyComing/assets/img/game/toolbar/max_hover_zh.png",
  toolbar_min_hover_en: "moneyComing/assets/img/game/toolbar/min_hover_en.png",
  toolbar_min_hover_zh: "moneyComing/assets/img/game/toolbar/min_hover_zh.png",
  toolbar_scatter_green: "moneyComing/assets/img/game/toolbar/scatter_green.png",
  toolbar_scatter_red: "moneyComing/assets/img/game/toolbar/scatter_red.png",
  toolbar_x10: "moneyComing/assets/img/game/toolbar/x10.png",

  spin_num_0: "moneyComing/assets/img/spin/num_0.png",
  spin_num_00: "moneyComing/assets/img/spin/num_00.png",
  spin_num_1: "moneyComing/assets/img/spin/num_1.png",
  spin_num_5: "moneyComing/assets/img/spin/num_5.png",
  spin_num_10: "moneyComing/assets/img/spin/num_10.png",
  spin_special_all_respin: "moneyComing/assets/img/spin/special_all_respin.png",
  spin_special_scatter_5: "moneyComing/assets/img/spin/special_scatter_5.png",
  spin_special_scatter_50: "moneyComing/assets/img/spin/special_scatter_50.png",
  spin_special_x2: "moneyComing/assets/img/spin/special_x2.png",
  spin_special_x5: "moneyComing/assets/img/spin/special_x5.png",
  spin_special_x10: "moneyComing/assets/img/spin/special_x10.png",

  audio_click: "moneyComing/assets/audio/click.mp3",
  audio_lock: "moneyComing/assets/audio/lock.mp3",
  audio_bgm: "moneyComing/assets/audio/bgm.mp3",
  audio_win_more: "moneyComing/assets/audio/win_more.mp3",
  audio_bet: "moneyComing/assets/audio/bet.mp3",
  audio_normal_stop: "moneyComing/assets/audio/normal_stop.mp3",
  audio_null_stop: "moneyComing/assets/audio/null_stop.mp3",
  audio_2x_stop: "moneyComing/assets/audio/2x_stop.mp3",
  audio_5x_stop: "moneyComing/assets/audio/5x_stop.mp3",
  audio_10x_stop: "moneyComing/assets/audio/10x_stop.mp3",
  audio_scatter_stop: "moneyComing/assets/audio/scatter_stop.mp3",
  audio_normal_win: "moneyComing/assets/audio/normal_win.mp3",
  audio_back_win: "moneyComing/assets/audio/back_win.mp3",
  audio_respin_play: "moneyComing/assets/audio/respin_play.mp3",
  audio_respin_ready: "moneyComing/assets/audio/respin_ready.mp3",
  audio_respin_stop: "moneyComing/assets/audio/respin_stop.mp3",
  audio_turntable_bg: "moneyComing/assets/audio/turntable_bg.mp3",
  audio_turntable_rotate: "moneyComing/assets/audio/turntable_rotate.mp3",
  audio_turntable_win: "moneyComing/assets/audio/turntable_win.mp3",
  audio_big_win: "moneyComing/assets/audio/big_win.mp3",
  audio_mega_win: "moneyComing/assets/audio/mega_win.mp3",
  audio_turntable_unlock: "moneyComing/assets/audio/turntable_unlock.mp3",
  audio_turntable_toggle: "moneyComing/assets/audio/turntable_toggle.mp3",
  audio_unlock: "moneyComing/assets/audio/unlock.mp3",

  vertical_winMore_dialog_bg: "moneyComing/assets/img/vertical/game/winMore/dialog_bg.png",

  vertical_frame_top: "moneyComing/assets/img/vertical/game/frame/top.png",
  vertical_frame_bottom: "moneyComing/assets/img/vertical/game/frame/bottom.png",
  vertical_frame_axis_base: "moneyComing/assets/img/vertical/game/frame/axis_base.png",
  vertical_frame_axis_bg: "moneyComing/assets/img/vertical/game/frame/axis_bg.png",

  vertical_toolbar_bg: "moneyComing/assets/img/vertical/game/toolbar/bg.png",
  vertical_toolbar_bet_amount_bg: "moneyComing/assets/img/vertical/game/toolbar/bet_amount_bg.png",
  vertical_toolbar_min_max_bg: "moneyComing/assets/img/vertical/game/toolbar/min_max_bg.png",
  vertical_toolbar_amount_selected:
    "moneyComing/assets/img/vertical/game/toolbar/amount_selected.png",
  vertical_toolbar_amount_list_bg:
    "moneyComing/assets/img/vertical/game/toolbar/amount_list_bg.png",

  vertical_autoSetting_bg: "moneyComing/assets/img/vertical/game/autoSetting/bg.png",
  vertical_autoSetting_box_bg: "moneyComing/assets/img/vertical/game/autoSetting/fang.png",

  spine_into_horizontal: "moneyComing/assets/spine/intoHorizontal/fx_kaichang.json",
  spine_into_vertical: "moneyComing/assets/spine/intoVertical/fx_kaichang_shu.json",
  spine_play: "moneyComing/assets/spine/play/fx_play.json",
  spine_suolian: "moneyComing/assets/spine/wheelLock/fx_suolian.json",
  spine_unlock: "moneyComing/assets/spine/unlock/fx_kaisuo.json",
  spine_lock: "moneyComing/assets/spine/lock/fx_guansuo.json",
  spine_light_round: "moneyComing/assets/spine/lightRound/fx_lunpan_guanghuan.json",
  spine_light_horizontal: "moneyComing/assets/spine/lightHorizontal/fx_daiji_heng.json",
  spine_wheel_finish: "moneyComing/assets/spine/wheelFinish/fx_zhongjiang.json",
  spine_wheel_toggle: "moneyComing/assets/spine/wheelToggle/fx_lunpan_qiehuan.json",
  spine_respin_frame: "moneyComing/assets/spine/respinFrame/fx_respins.json",
  spine_status_frame: "moneyComing/assets/spine/statusFrame/fx_kuang.json",
  spine_scatter_red: "moneyComing/assets/spine/scatterRed/fx_scatter_red.json",
  spine_scatter_green: "moneyComing/assets/spine/scatterGreen/fx_scatter_lv.json",
  spine_x2: "moneyComing/assets/spine/x2/fx_tubiao_lv.json",
  spine_x5: "moneyComing/assets/spine/x5/fx_tubiao_zi.json",
  spine_x10: "moneyComing/assets/spine/x10/fx_tubiao_fen.json",
  spine_num_0: "moneyComing/assets/spine/num_0/fx_shuzi_0.json",
  spine_num_00: "moneyComing/assets/spine/num_00/fx_shuzi_00.json",
  spine_num_1: "moneyComing/assets/spine/num_1/fx_shuzi_1.json",
  spine_num_5: "moneyComing/assets/spine/num_5/fx_shuzi_5.json",
  spine_num_10: "moneyComing/assets/spine/num_10/fx_shuzi_10.json",
  spine_respin: "moneyComing/assets/spine/respin/fx_wheel.json",
  spine_superwin: "moneyComing/assets/spine/superwin/superwin.json",
  spine_bigwin: "moneyComing/assets/spine/bigwin/bigwin.json",
  spine_megawin: "moneyComing/assets/spine/megawin/megawin.json",
  spine_coin_erupt: "moneyComing/assets/spine/coinErupt/jinbi.json",
  spine_coin_drop: "moneyComing/assets/spine/coinDrop/jinbiyu.json",
  spine_respin_one_lizi: "moneyComing/assets/spine/respinOneLizi/fx_lizi_B.json",
  spine_respin_two_lizi: "moneyComing/assets/spine/respinTwoLizi/fx_lizi_A.json",
  spine_scatter_lizi: "moneyComing/assets/spine/scatterLizi/fx_lizituowei.json",
  spine_scatter_lizi_vertical: "moneyComing/assets/spine/scatterLiziVertical/fx_lizitw_shu.json",
  spine_erupt_shine: "moneyComing/assets/spine/eruptShine/fx_bd.json",

  vertical_spine_light: "moneyComing/assets/spine/lightVertical/fx_daiji_shu_shaoguang.json",

  ...stgCommonManifest,
  ...gameCommonManifest,
};

/** @description loading页资源 */
const loadingManifest = {
  loading_logo_en: "moneyComing/assets/img/logo/en.png",
  loading_logo_zh: "moneyComing/assets/img/logo/zh.png",
  loading_logo_tc: "moneyComing/assets/img/logo/tc.png",
  loading_bg: "moneyComing/assets/img/loading/bg.png",
  loading_flash: "moneyComing/assets/img/loading/flash.png",
  loading_arrow: "moneyComing/assets/img/loading/arrow.png",
  loading_silder_1: "moneyComing/assets/img/loading/silder_1.png",
  loading_silder_2: "moneyComing/assets/img/loading/silder_2.png",
  loading_progress_bar_bg: "moneyComing/assets/img/loading/progress_bar_bg.png",
  loading_progress_bar: "moneyComing/assets/img/loading/progress_bar.png",
  loading_login_btn: "moneyComing/assets/img/loading/login_btn.png",

  spine_intro_1: "moneyComing/assets/spine/introOne/jiazai01.json",
  spine_intro_2: "moneyComing/assets/spine/introTwo/jiazai02.json",

  vertical_loading_bg: "moneyComing/assets/img/vertical/loading/bg.png",
};

export { gameManifest, loadingManifest };
